runtime: java11
entrypoint: 'java -jar palace-0.0.1-SNAPSHOT.war'
instance_class: F2

handlers:
- url: /.*
  script: this field is required, but ignored

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
